# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0002_memberinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
