# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_info', '0003_auto_20171004_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
